version: '3.8'
services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Adjust based on your Vite configuration
    volumes:
      - .:/app # Mount current directory to /app in the container
      - /app/node_modules # Prevent conflicts between host and container node_modules
    tty: true # Keep the terminal open for interaction
